version: 2.1

build-filters: &build-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/


jobs:
  # microservice-integration-testing-with-behave
  timezone-example:
    working_directory: ~/educative-tutorials
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd microservice-integration-testing-with-behave
            make build
      - run:
          name: Integration tests
          command: |
            cd ~/educative-tutorials/microservice-integration-testing-with-behave
            make test-integration

workflows:
  version: 2
  pipeline:
    jobs:
      - timezone-example:
          filters: *build-filters
